# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  displayName: 'Run Scripts'
  inputs: 
    targetType: 'filePath' # Optional. Options: filePath, inline
    filePath: 'myScripts/script1.sh'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
    npm test
  displayName: 'npm install and build'

- script: 
   echo 'Hello SPidy'
  displayName: Hello spidy 

# Python script
# Run a Python file or inline script
- task: PythonScript@0
  displayName: 'Run Python Script'
  inputs:
    scriptSource: 'filePath' # Options: filePath, inline
    scriptPath: myScripts/pythonScript.py
    #script: # Required when scriptSource == inline

#Publish test
- task: Npm@1
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: 'feed1'